name: moqred
description: Transaction-based application

publish_to: "none"
version: 0.10.10+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: 12.1.3
  infinite_scroll_pagination: ^5.1.1
  shimmer: ^3.0.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  sqflite_common_ffi_web: ^0.4.3+1
  json_annotation: ^4.9.0
  from_css_color: ^2.0.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  json_path: ^0.7.2
  page_transition: ^2.1.0
  provider: ^6.1.2
  rive: ^0.12.2
  shared_preferences: ^2.2.2
  shared_preferences_android: ^2.2.1
  shared_preferences_foundation: ^2.3.4
  shared_preferences_platform_interface: ^2.3.1
  shared_preferences_web: ^2.2.1
  table_calendar: ^3.1.1
  timeago: ^3.6.1
  url_launcher: ^6.2.5
  url_launcher_android: ^6.3.0
  url_launcher_platform_interface: ^2.3.2
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.15.0
  webview_flutter_platform_interface: ^2.10.0
  auto_size_text: ^3.0.0
  collection: ^1.18.0
  data_table_2: ^2.5.10
  syncfusion_flutter_datagrid: ^29.1.33
  dropdown_button2: ^2.3.9
  easy_debounce: ^2.0.1
  equatable: ^2.0.5
  expandable: ^5.0.1
  file_picker: ^8.0.3
  floating_bottom_navigation_bar: ^1.5.2
  font_awesome_flutter: ^10.9.1

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  image: 4.2.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  json_serializable: ^6.7.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
  image_path: "assets/images/app_launcher_icon.png"
  adaptive_icon_background: "#00000000"
  adaptive_icon_foreground: "assets/images/adaptive_foreground_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
    - assets/schema.sql
